### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by KillaMeep** [hearmeneigh/dataset-rising#5]
Anytime I run the train, I get this error. Any idea what could be causing it?

`
Traceback (most recent call last):
  File "/usr/local/bin/dr-train", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/train/dr_train.py", line 5, in main
    vendor_main()
  File "/usr/local/lib/python3.10/dist-packages/train/vendor/huggingface/diffusers/train_text_to_image.py", line 1008, in main
    model_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_condition.py", line 876, in forward
    if "text_embeds" not in added_cond_kwargs:
TypeError: argument of type 'NoneType' is not iterable
`

Heres the full output:

01/20/2024 04:10:39 - INFO - train.vendor.huggingface.diffusers.train_text_to_image - ***** Running training *****
01/20/2024 04:10:39 - INFO - train.vendor.huggingface.diffusers.train_text_to_image -   Num examples = 512
01/20/2024 04:10:39 - INFO - train.vendor.huggingface.diffusers.train_text_to_image -   Num Epochs = 100
01/20/2024 04:10:39 - INFO - train.vendor.huggingface.diffusers.train_text_to_image -   Instantaneous batch size per device = 1
01/20/2024 04:10:39 - INFO - train.vendor.huggingface.diffusers.train_text_to_image -   Total train batch size (w. parallel, distributed & accumulation) = 20
01/20/2024 04:10:39 - INFO - train.vendor.huggingface.diffusers.train_text_to_image -   Gradient Accumulation steps = 20
01/20/2024 04:10:39 - INFO - train.vendor.huggingface.diffusers.train_text_to_image -   Total optimization steps = 2600
Steps:   0%|                                                                                                                                                | 0/2600 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/dr-train", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/train/dr_train.py", line 5, in main
    vendor_main()
  File "/usr/local/lib/python3.10/dist-packages/train/vendor/huggingface/diffusers/train_text_to_image.py", line 1008, in main
    model_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/models/unet_2d_condition.py", line 876, in forward
    if "text_embeds" not in added_cond_kwargs:
TypeError: argument of type 'NoneType' is not iterable

**Comment by hearmeneigh** [comment]
What is the base model you're training from? If it's SDXL, you will need to use `dr-train-xl` instead of `dr-train`.

Otherwise, please share the full command-line command and parameters you're executing.

**Comment by KillaMeep** [comment]
Training off of e621 rising.

**Comment by hearmeneigh** [comment]
For `e621-rising-v3`, definitely use `dr-train-xl`.

**Comment by KillaMeep** [comment]
Ah alrighty. Thanks!
